"""Remove rating column from Appearance

Revision ID: c10be3ec604d
Revises: 3b12ea98eedb
Create Date: 2024-10-14 04:11:55.968034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c10be3ec604d'
down_revision = '3b12ea98eedb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appearance', schema=None) as batch_op:
        batch_op.drop_column('rating')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appearance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
