"""Add rating to Appearance

Revision ID: fac14bac3a33
Revises: c10be3ec604d
Create Date: 2024-10-14 04:34:36.692808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fac14bac3a33'
down_revision = 'c10be3ec604d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appearance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appearance', schema=None) as batch_op:
        batch_op.drop_column('rating')

    # ### end Alembic commands ###
